custom_components/sector/__init__.py
custom_components/sector/alarm_control_panel.py
custom_components/sector/config_flow.py
custom_components/sector/const.py
custom_components/sector/coordinator.py
custom_components/sector/lock.py
custom_components/sector/sensor.py
custom_components/sector/switch.py

Clean code
- isort
- flake8
- move hub to coordinator file
- other minor changes

Clean code

---

custom_components/sector/coordinator.py

Remove isonline check for solving pending alarms (mobile connections)

Fix isonline error

---

readme.md

I updated the HACS Badge URL to the new hacs/integration.

Update HACS URL

---

custom_components/sector/__init__.py
custom_components/sector/alarm_control_panel.py
custom_components/sector/const.py
readme.md

Cleanup code and make compliant

Cleanup code and make compliant

---

custom_components/sector/config_flow.py

Add update interval to Initial configuration of config flow

Set options already in initial config flow

---

custom_components/sector/manifest.json
hacs.json

To version v0.3.5
Due to new enums will require HA version 2022.5.0

Make v0.3.5

---

custom_components/sector/__init__.py
custom_components/sector/alarm_control_panel.py
custom_components/sector/coordinator.py

Additional cleanup

---

custom_components/sector/__init__.py
custom_components/sector/alarm_control_panel.py
custom_components/sector/config_flow.py
custom_components/sector/const.py
custom_components/sector/coordinator.py
custom_components/sector/lock.py
custom_components/sector/strings.json
custom_components/sector/translations/en.json
custom_components/sector/translations/no.json
custom_components/sector/translations/se.json

Config flow
- Move things to options fixes #44 #28 
- Remove possibility to exclude lock fixes #39 
- Prepare to handle late state changes for changed by discussed in #47 
- Additional cleanup, imports, sorts

Config flow mods

---

custom_components/sector/alarm_control_panel.py
custom_components/sector/coordinator.py
custom_components/sector/lock.py

Generic improve error handling

Improve error handling

---

custom_components/sector/__init__.py
custom_components/sector/const.py

Fix migration use CONF_USERNAME instead of CONF_USERID
Fixes #73

Fix migration issue CONF_USERNAME

---

custom_components/sector/strings.json
custom_components/sector/translations/en.json
custom_components/sector/translations/no.json
custom_components/sector/translations/se.json

Fix strings and translations

---

custom_components/sector/config_flow.py

Better handling of errors
Does not fix but better addressing for #76

Handle errors in config flow

---

custom_components/sector/__init__.py
custom_components/sector/alarm_control_panel.py
custom_components/sector/lock.py

Address migrations errors and entry data errors

---

.gitignore
custom_components/sector/config_flow.py
custom_components/sector/coordinator.py

Fix response text

---

.gitignore
custom_components/sector/__init__.py
custom_components/sector/alarm_control_panel.py
custom_components/sector/config_flow.py
custom_components/sector/const.py
custom_components/sector/coordinator.py
custom_components/sector/lock.py
custom_components/sector/sensor.py
custom_components/sector/strings.json
custom_components/sector/switch.py
custom_components/sector/translations/en.json
custom_components/sector/translations/no.json
custom_components/sector/translations/se.json

Redesign data fetch
Fix bugs
Fixes #76
Fixes #56 
Fixes #24 
Fixes #53 
Fixes #54

Redesign data

---

custom_components/sector/coordinator.py

Fix coordinator error handling
Fixes #84

Fix coordinator

---

custom_components/sector/config_flow.py
custom_components/sector/coordinator.py

Fix beta8 issues

---

custom_components/sector/coordinator.py
custom_components/sector/lock.py
custom_components/sector/sensor.py
custom_components/sector/switch.py

Added a few more validations and using dict.get() to avoid exceptions on empty return values.
It is still needed a few more places, I guess:
```
2022-06-12 10:52:21 ERROR (MainThread) [homeassistant.components.lock] Error while setting up sector platform for lock
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/sector/lock.py", line 34, in async_setup_entry
for lock, lock_data in panel_data["lock"].items():
KeyError: 'lock'
```

Use dict.get()

---

custom_components/sector/alarm_control_panel.py
custom_components/sector/coordinator.py
custom_components/sector/lock.py
custom_components/sector/sensor.py
custom_components/sector/switch.py

Finalize data
Improve error handling

Finalize data

---

custom_components/sector/alarm_control_panel.py
custom_components/sector/lock.py
custom_components/sector/sensor.py
custom_components/sector/switch.py

Various cleaning checks

---

custom_components/sector/alarm_control_panel.py
custom_components/sector/lock.py
custom_components/sector/sensor.py
custom_components/sector/switch.py

_attr_has_entity_name
deviceinfo -> _attr_device_info

Fix has_entity_name

---

custom_components/sector/coordinator.py

Fix login error

---

custom_components/sector/coordinator.py

Handle alarm not online
Improved handling no api response
Related to #96

Handle alarm online

---

custom_components/sector/coordinator.py

Modify data on api request to ensure last state present

Modify data faster

---

custom_components/sector/coordinator.py

Reduce warnings in log

---

custom_components/sector/coordinator.py

Fix user_to_set

---

custom_components/sector/coordinator.py

Fix online issue

---

custom_components/sector/coordinator.py

Redact data

---

custom_components/sector/lock.py

Fixes: #150
Added missing curly braces for the regex pattern.

Added curly braces for the number of digits regex pattern

---

custom_components/sector/binary_sensor.py

Fix binary sensor unique id issue

---

custom_components/sector/coordinator.py

update so  that data can be added to the data dictonary in the loop process

Fix multi installation issue

---

custom_components/sector/__init__.py
custom_components/sector/alarm_control_panel.py
custom_components/sector/binary_sensor.py
custom_components/sector/camera.py
custom_components/sector/client.py
custom_components/sector/config_flow.py
custom_components/sector/const.py
custom_components/sector/coordinator.py
custom_components/sector/diagnostics.py
custom_components/sector/endpoints.py
custom_components/sector/lock.py
custom_components/sector/manifest.json
custom_components/sector/sensor.py
custom_components/sector/switch.py

Sector Alarm has started to transition to a new API. With the newer hardware this allows for additional sensors in most devices including temperature, humidity, door states etc.
This is still WIP but will extend the capabilities vastly.

Overhaul of API

---

custom_components/sector/entity.py

Fix debug to use the correct variables, this breaks the flow when initializing the system

bug-fix: entry.py debug error

---

custom_components/sector/alarm_control_panel.py

Fix alarm state

---

custom_components/sector/client.py
custom_components/sector/config_flow.py
custom_components/sector/const.py
custom_components/sector/translations/en.json
custom_components/sector/translations/se.json

Fix config flow

---

custom_components/sector/__init__.py
custom_components/sector/config_flow.py
custom_components/sector/model.py

Add migration to not handle migration
